# Generated by Django 3.2.5 on 2021-08-06 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField(default=0)),
                ('image', models.FileField(default=None, upload_to='')),
                ('start_date', models.DateField()),
                ('d1', models.TextField(default='', verbose_name='Monday')),
                ('d2', models.TextField(default='', verbose_name='Tuesday')),
                ('d3', models.TextField(default='', verbose_name='Wednesday')),
                ('d4', models.TextField(default='', verbose_name='Thursday')),
                ('d5', models.TextField(default='', verbose_name='Friday')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
